### ISSUE TITLE
Suspicious Installer

### ISSUE THREAD

**Issue by Neonit** [alessandrofrancesconi/gimp-plugin-bimp#231] opened 2020-03-16 10:26 UTC
The installer has a slightly suspicious score on VirusTotal: https://www.virustotal.com/gui/file/570e35f5a2561d8d0bed7e9aa74a4783fdf4b19efabb467be90f8ec690f9ff53/detection

However, installing the plug-in manually is very easy. I would add instructions for that.

1. If you have the installer, *gimp-plugin-bimp_win32.exe*, use an extraction tool like [7-Zip](https://www.7-zip.org/) to unpack it.
2. Locate your GIMP plugin directory, which should be under *C:/Users/&lt;username>/AppData/Roaming/GIMP/&lt;version>/plug-ins*.
3. In the plugin directory, create a folder named *bimp*. From the extracted files, copy the following files into the newly created *bimp* folder:
    - *bimp-locale*
    - *bimp.exe*
4. (Re-)Start GIMP.

**Comment by Bebop182** [comment] 2020-05-09 18:14
BIMP appears in the application list, however trying to remove it there shows that the path to the uninstaller is wrong. Manually searching for it an running it won't remove BIMP at all.

**Comment by alessandrofrancesconi** [comment] 2021-01-07 22:50
Duplicate of #246

**Closed by alessandrofrancesconi** 2021-01-07 22:50 UTC
